/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as scientify4Sol from "./Scientify4.sol";
export { Scientify__factory } from "./Scientify__factory";
