/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Scientify__factory } from "./Scientify__factory";
export { Scientify4__factory } from "./Scientify4__factory";
