/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISP } from "./ISP";
export type { ISPHook } from "./ISPHook";
export type { IVersionable } from "./IVersionable";
