/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as scientify4Sol from "./Scientify4.sol";
export type { scientify4Sol };
export type { Scientify } from "./Scientify";
