/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVersionable,
  IVersionableInterface,
} from "../../../../../@ethsign/sign-protocol-evm/src/interfaces/IVersionable";

const _abi = [
  {
    inputs: [],
    name: "version",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IVersionable__factory {
  static readonly abi = _abi;
  static createInterface(): IVersionableInterface {
    return new Interface(_abi) as IVersionableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVersionable {
    return new Contract(address, _abi, runner) as unknown as IVersionable;
  }
}
